DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS user CASCADE;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS item_type CASCADE;
DROP SEQUENCE IF EXISTS global_seq CASCADE;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE user
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    email      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    enabled    BOOLEAN   DEFAULT TRUE  NOT NULL
);
CREATE UNIQUE INDEX user_unique_email_idx ON user (email);

CREATE TABLE user_role
(
    user_id INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    role    VARCHAR(255),
    CONSTRAINT user_role_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
);

CREATE TABLE item_type
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX item_type_unique_name_idx ON item_type (name);

CREATE TABLE item
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
    name            VARCHAR(255)    NOT NULL,
    date_memorable  DATE            NOT NULL,
    item_type_id    INTEGER         NOT NULL,
    CONSTRAINT name_item_type_id_idx UNIQUE (name, item_type_id),
    FOREIGN KEY (item_type_id) REFERENCES item_type (id) ON DELETE CASCADE
);
